name: multiplayer
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # STATE MGMT
  get: ^4.6.6
  # API 
  dio: ^5.4.1
  # Local Storage
  get_storage: ^2.1.1
  # flutter toast
  fluttertoast: ^8.2.4
  #Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.1.0
  firebase_messaging: ^14.7.16
  firebase_analytics: ^10.8.6

  #audio
  assets_audio_player: ^3.1.1

  # UI Design

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/audio/
