name: multiplayer
description: "multiplayer Flutter SDK 3.16.2 || Dart SDK 3.2.2"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # STATE MGMT
  get: ^4.6.6
  # API 
  dio: ^5.4.1
  # Local Storage
  get_storage: ^2.1.1
  # flutter toast
  fluttertoast: ^8.2.4

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.1.0
  firebase_messaging: ^14.7.16
  firebase_analytics: ^10.8.6
  flutter_local_notifications: ^17.0.0
  firebase_in_app_messaging: ^0.7.4+17

  # Audio
  assets_audio_player: ^3.1.1

  # UI Design
  flutter_gradient_colors: ^2.1.1

  # In App Purchase
  in_app_purchase: ^3.1.13

  # App Update
  upgrader: ^10.0.0
  
  # Design
  animated_background: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/audio/
